version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
      timezone: Europe/London

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
      timezone: Europe/London
    ignore:
      - dependency-name: "jetty-bom"
        update-types: ["version-update:semver-major"]
