language: java
jdk:
 - openjdk11
env:
 global:
  - GITHUB_ACTOR=araqnid
  - secure: "BLN6u9NCNVPVMh//cEUhNzZaWX2865bt8J28BQRXqaC85m5Cmkz9FB/Qhav8B3oD3EHdmtw6SEzQC1CF+jW45VqdlnTF7ghRjIlivQh5fjK2/IjjyAI/2Csyrw3s5L8D1N5d/KJGP8ChK5vVp73YwbEh3TDcHYVmCTAFg2G30iUWBIlINtJU581tl3MIPp7VKRtE9pxhBk2DmBnohnEEN0JLSfMPaZjdxXGQyb69mXWyH4123PXMYL8mDAi+APb4MUHDzPjgHII5X1tkFWjJIuUM5B7GgC3e1vbaR6t9rg1iOrTeQDZJxPGERYQaFw4io6L0doE5P0v8rw3iq087trZL8hFZfoZ6SQxgx9A0H+8yGMCBRbHvigdJF0VeTqhpLyUgSsvVMNLgPTXk4cteI+0vm2vCdm1beFQeF2QzxJd51TijRQr0SsL15QNkR0DIKONHLR+Xj9+YgEgYgTRQuLbw5/ILLXL+YNG8NeGjFsEWL+1R7GvqdHjVtNli3WQfxKDPByC0qCrr/bJfIonx2mc4UIWl1FjBM1VcvJbAAu06/irqtQP6h+CH2KvXz5IiOYszRzGUPiMurPfiVMy9JXWFobVO4wDDMWIdZz4g9aJvjR/79UY4bsCHR7tTA8MTKJ2TlGGRgdHMeH1AlGSvbU/QElclOq80jLnmyxk0+Zs="
